const GLOBALLY_UNIQUE_IDENTIFIER = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
const FRAME_TYPES = {
    CONTINUATION: 0,
    TEXT: 1,
    BINARY: 2,
    CLOSE: 8,
    PING: 9,
    PONG: 10
}
const SECOND = 1000;
const FIXED_LENGTH = 2;
export { GLOBALLY_UNIQUE_IDENTIFIER, FRAME_TYPES, SECOND, FIXED_LENGTH };